const YAKU = [
  { id: "riichi", name: "Riichi", group: "common", overlay: "riichi.png" },
  { id: "tsumo", name: "Tsumo", group: "common", overlay: "tsumo.PNG" },
  { id: "ippatsu", name: "Ippatsu", group: "common", overlay: "ippatsu.png" },
  { id: "double_riichi", name: "Double Riichi", group: "common", overlay: "double_riichi.PNG" },
  { id: "tanyao", name: "Tanyao", group: "common", overlay: "tanyao.PNG" },
  { id: "pinfu", name: "Pinfu", group: "common", overlay: "pinfu.png" },
  { id: "yakuhai", name: "Yakuhai", group: "common", overlay: "yakuhai.PNG" },
  { id: "iipeikou", name: "Iipeikou", group: "common", overlay: "iipeikou.PNG" },
  { id: "haitei_raoyue", name: "Haitei (last draw)", group: "common", overlay: "haitei_raoyue.PNG" },
  { id: "hourei_raoyui", name: "Houtei (last discard)", group: "common", overlay: "hourei_raoyui.PNG" },
  { id: "rinshan_kaihou", name: "Rinshan", group: "common", overlay: "rinshan_kaihou.PNG" },
  { id: "chankan", name: "Chankan", group: "common", overlay: "chankan.PNG" },
  { id: "chiitoitsu", name: "Chiitoi", group: "common", overlay: "chiitoitsu.PNG" },
  { id: "toitoi", name: "Toitoi", group: "common", overlay: "toitoi.PNG" },
  { id: "sanankou", name: "Sanankou", group: "common", overlay: "sanankou.PNG" },
  { id: "sanshoku_doujun", name: "Sanshoku Dojun (same seq)", group: "common", overlay: "sanshoukou_doujun.PNG" },
  { id: "iitsuu", name: "Ittsuu", group: "common", overlay: "iitsuu.PNG" },
  { id: "honitsu", name: "Honitsu", group: "common", overlay: "honitsu.png" },
  { id: "chinitsu", name: "Chinitsu", group: "common", overlay: "chinitsu.PNG" },
  { id: "chanta", name: "Chanta (term+hon)", group: "common", overlay: "chanta.PNG" },
  { id: "junchan", name: "Junchan (term)", group: "common", overlay: "junchan.PNG" },
  { id: "honroutou", name: "Honroutou (all term+hon)", group: "common", overlay: "honroutou.PNG" },
  { id: "shousangan", name: "Shousangen (3 lil drag)", group: "common", overlay: "shousangan.PNG" },
  { id: "sankantsu", name: "Sankantsu (3 kans)", group: "common", overlay: "sankantsu.PNG" },
  { id: "sanshoku_doukou", name: "Sanshoku Dokou (same tripl.)", group: "common", overlay: "sanshoukou_doukou.PNG" },
  { id: "ryanpeikou", name: "Ryanpeikou", group: "common", overlay: "ryanpeikou.PNG" },
  { id: "nagashi_mangan", name: "Nagashi Mangan", group: "common", overlay: "nagashi_mangan.PNG" },
  { id: "kokushi_musou", name: "Kokushi (13-orph)", group: "yakuman", overlay: "kokushi_musou.PNG" },
  { id: "suuankou", name: "Suuankou (4 cl. tripl)", group: "yakuman", overlay: "suuankou.PNG" },
  { id: "daisangen", name: "Daisangen (3 drag trip)", group: "yakuman", overlay: "daisangen.PNG" },
  { id: "shousuushii", name: "Shousuushii (4 lil winds)", group: "yakuman", overlay: "shousuushii.PNG" },
  { id: "daisuushii", name: "Daisuushii (4 big winds)", group: "yakuman", overlay: "daisuushii.PNG" },
  { id: "tsuuiisou", name: "Tsuuiisou (all hon)", group: "yakuman", overlay: "tsuuiisou.PNG" },
  { id: "chinroutou", name: "Chinroutou (all term)", group: "yakuman", overlay: "chinroutou.PNG" },
  { id: "ryuuiisou", name: "Ryuuiisou (all green)", group: "yakuman", overlay: "ryuuiisou.PNG" },
  { id: "chuuren_poutou", name: "Chuuren (9gates)", group: "yakuman", overlay: "chuuren_poutou.PNG" },
  { id: "suukantsu", name: "Suukantsu (4 kan)", group: "yakuman", overlay: "suukantsu.PNG" },
  { id: "tenhou", name: "Tenhou", group: "yakuman", overlay: "tenhou.PNG" },
  { id: "chiihou", name: "Chiihou", group: "yakuman", overlay: "chiihou.PNG" },
  { id: "kazoe_yakuman", name: "Kazoe (counted yakuman)", group: "yakuman", overlay: "kazoe_yakuman.PNG" }
];

export default YAKU;